# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: yamldemo_$(Date:yyyyMMdd)$(Rev:.r)
parameters:
  - name: ProjectName
    displayName: "Select Project Name to Build"
    type: string
    default: Payment
    values:
        - Payment
        - Profile
        - Admin
        - onlinepayment
  - name: EnvironmentType
    displayName: 'Select the Envionment'
    type: string
    default: QA
    values:
        - QA
        - Dev
        - Security

  - name: UnitTestRun
    displayName: 'Do you want to Run Unit Test?'
    type: boolean
    default: true

  - name: DeployCheck
    displayName: "Do you want to Deploy?"
    type: boolean
    default: true

trigger: none
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
     vmImage: 'ubuntu-latest'
    steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script for ${{ parameters.ProjectName }}'
- ${{ if eq(parameters.UnitTestRun, true) }}:
  - stage: UnitTestRun
    jobs:
    - job: rununitest
      pool:
     vmImage: 'ubuntu-latest'
      steps:
       - task: Bash@3
         inputs:
           targetType: 'inline'
           script: |
             echo "Unit test Setup"
        
- ${{ if eq(parameters.DeployCheck, true) }}:
  - stage: Deploy
    jobs:
    - job: deployapp
      pool:
        vmImage: 'ubuntu-latest'
      steps:
       - task: Bash@3
         inputs:
           targetType: 'inline'
           script: |
             echo "Deploy Setup.."

pool:
  name: default
  vmImage: ubuntu-latest
# pool:
#   name: 'Hosted-Agent'
#   demands:
#   - Agent.Version -gtVersion 2.163.1
